dist: trusty
sudo: required
language: python

python:
 - "2.7"

# uncomment and edit the following line if your project needs to run something other than `rake`:

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y inkscape
  
install: true
 
 
script:
  - ls -l
  - inkscape -z -e "Ergonomic Background Screen (1920x1080).png" -w 1920 -h 1080 "Ergonomic Background Screen.svg"
  - inkscape -z -e "Ergonomic Background Screen (800x600).png" -w 800 -h 600 "Ergonomic Background Screen.svg"
before_deploy: 
  - ls -l
  - tar -cvzf OpenErgonomics.tar.gz *.png

branches:
  only:
    - gh-pages
