dist: trusty
sudo: required
language: python

python:
 - "2.7"

# uncomment and edit the following line if your project needs to run something other than `rake`:

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y inkscape
  
install: true
 
 
script: true
before_deploy: true

branches:
  only:
    - gh-pages
