title: Openergonomics
description: A project for setting up your work environment for optimal comfort.
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
